name: run npm-version pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Current Version Checkout
        run: npm run version

      - name: 'run version change'
        uses: ./
        with:
          version: '1.0.1'

      - name: Current Version Checkout
        run: npm run version